name: Makefile CI

on:
  push:
    branches:
      - Submission
  pull_request:
    branches:
      - Submission

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    # - uses: ocaml/setup-ocaml@v1.1.11
    
    - name: Install everything
      run:  sudo apt install ocaml llvm llvm-runtime m4 opam ocamlbuild
    - name: Install llvm.6.0.0
      run:  | 
            opam init
            opam install llvm.6.0.0
            eval $(opam config env)
    - name: Compile Dice Compiler
      run: make
    - name: Compile A Program
      run: ./compile.sh tests/test-hello.roll
    - name: Test
      run: ./test.sh tests/test-hello.roll
    
