name: Makefile CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - ubuntu-18.04
        include:
        - os:                  'ubuntu-latest'
          llvm:                'llvm.10.0.0'
        - os:                  'ubuntu-18.04'
          llvm:                'llvm.6.0.0'

      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    
    - name: Install everything
      run:  | 
            sudo apt install ocaml llvm llvm-runtime m4 opam ocamlbuild
            opam init --yes
            opam install ${{ matrix.llvm }} --yes
            eval $(opam config env)
    - name: Compile Dice Compiler
      run: make
    - name: Compile A Program
      run: ./compile.sh tests/test-hello.roll
    - name: Test
      run: make test
    
